on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: encode
      run: python3 main.py gda
    - uses: actions/upload-artifact@v2
      with:
        name: build
        path: build